# Data Preprocessing

- Clean stopped words, punctuation, replace URL template with '__url__' tokens
- Fill NaN/null values with empty string

In [2]:
%pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.9.4)
Requirement already satisfied: click in C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in C:\Users\Windows\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

## Importing libraries

In [2]:
import pandas as pd
import re, nltk, string #RegEx
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer

In [5]:
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('averaged_perceptron_tagger', quiet=True)
nltk.download('averaged_perceptron_tagger_eng', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('stopwords', quiet=True)

True

## Loading dataset

In [4]:
raw_dataset = pd.read_csv('./data/raw/enron_spam_data.csv')

## Previewing samples in dataset

In [6]:
pd.set_option('display.max_colwidth', None)
raw_dataset[["Subject", "Message"]].head(20)

                                       Subject  \
0                 christmas tree farm pictures
1                     vastar resources , inc .
2                 calpine daily gas nomination
3                                   re : issue
4                    meter 7268 nov allocation
5                     mcmullen gas for 11 / 99
6                        meter 1517 - jan 1999
7                          duns number changes
8                                   king ranch
9                       re : entex transistion
10                           entex transistion
11          lst rev dec . 1999 josey ranch nom
12         2 nd rev dec . 1999 josey ranch nom
13                        unify close schedule
14                       meter 1431 - nov 1999
15                       meter 1431 - nov 1999
16                           y 2 k - texas log
17                         re : lyondell citgo
18   hpl fuel gas buy - back for december 1999
19  ua 4 - meter 1441 for 11 / 97 - falfurrias

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Message
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          NaN
1   gary , production from the high island larger block a - 1 # 2 commenced on\nsaturday at 2 : 00 p . m . at about 6 , 500 gross . carlos expects between 9 , 500 and\n10 , 000 gross for tomorrow . vastar owns 68 % of the gross production .\ngeorge x 3 - 6992\n- - - - - - - - - - - - - - - - - - - - - - forwarded by george weissman / hou / ect on 12 / 13 / 99 10 : 16\nam - - - - - - - - - - - - - - - - - - - - - - - - - - -\ndaren j farmer\n12 / 10 / 99 10 : 38 am\nto : carlos j rodriguez / hou / ect @ ect\ncc : george weissman / hou / ect @ ect , melissa graves / hou / ect @ ect\nsubject : vastar resources , inc .\ncarlos ,\nplease call linda and get everything set up .\ni ' m going to estimate 4 , 500 coming up tomorrow , with a 2 , 000 increase each\nfollowing day based on my conversations with bill fischer at bmar .\nd .\n- - - - - - - - - - - - - - - - - - - - - - forwarded by daren j farmer / hou / ect on 12 / 10 / 99 10 : 34\nam - - - - - - - - - - - - - - - - - - - - - - - - - - -\nenron north america corp .\nfrom : george weissman 12 / 10 / 99 10 : 00 am\nto : daren j farmer / hou / ect @ ect\ncc : gary bryan / hou / ect @ ect , melissa graves / hou / ect @ ect\nsubject : vastar resources , inc .\ndarren ,\nthe attached appears to be a nomination from vastar resources , inc . for the\nhigh island larger block a - 1 # 2 ( previously , erroneously referred to as the\n# 1 well ) . vastar now expects the well to commence production sometime\ntomorrow . i told linda harris that we ' d get her a telephone number in gas\ncontrol so she can provide notification of the turn - on tomorrow . linda ' s\nnumbers , for the record , are 281 . 584 . 3359 voice and 713 . 312 . 1689 fax .\nwould you please see that someone contacts linda and advises her how to\nsubmit future nominations via e - mail , fax or voice ? thanks .\ngeorge x 3 - 6992\n- - - - - - - - - - - - - - - - - - - - - - forwarded by george weissman / hou / ect on 12 / 10 / 99 09 : 44\nam - - - - - - - - - - - - - - - - - - - - - - - - - - -\n" linda harris " on 12 / 10 / 99 09 : 38 : 43 am\nto : george weissman / hou / ect @ ect\ncc :\nsubject : hi a - 1 # 2\neffective 12 - 11 - 99\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| mscf / d | min ftp | time |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 4 , 500 | 9 , 925 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 6 , 000 | 9 , 908 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 8 , 000 | 9 , 878 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 10 , 000 | 9 , 840 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 12 , 000 | 9 , 793 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 14 , 000 | 9 , 738 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 16 , 000 | 9 , 674 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 18 , 000 | 9 , 602 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 20 , 000 | 9 , 521 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 22 , 000 | 9 , 431 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 24 , 000 | 9 , 332 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 26 , 000 | 9 , 224 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 28 , 000 | 9 , 108 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 30 , 000 | 8 , 982 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 32 , 000 | 8 , 847 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 34 , 000 | 8 , 703 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |\n| | | |\n| 36 , 000 | 8 , 549 | 24 hours |\n| | | |\n| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       - calpine daily gas nomination 1 . doc

## Preprocessing dataset

In [7]:
# Initializing the empty preprocessed dataset first
preprocessed_dataset = pd.DataFrame({'Label': [],
                                     'Subject': [],
                                     'Message': []
                                     })

In [8]:
STOP_WORDS = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
# Convert labels from NLTK POS Tag to WordNet POS Tag
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [10]:
def preprocessing_message(text: str) -> str:
    # Fill null/NaN values with empty string
    cleaned = '' if pd.isna(text) else str(text)
    
    # Remove Unicode characters
    cleaned = cleaned.encode('ascii', 'ignore').decode('ascii')
    
    # Remove HTML tags
    cleaned = re.sub(r'<[^>]+>', ' ', cleaned)
        
    # Replace https string into token '__url__', with example: "https://example.net" or "example.net"
    cleaned = re.sub(r'^(http[s]?:\\/\\/(www\\.)?|ftp:\\/\\/(www\\.)?|www\\.){1}([0-9A-Za-z-\\.@:%_\+~#=]+)+((\\.[a-zA-Z]{2,3})+)(/(.)*)?(\\?(.)*)?', 
                     '__url__', cleaned)
    
    cleaned = re.sub(r'\b\d+\b', ' ', cleaned)
    
    # Removing punctuation, replace it with space 
    cleaned = re.sub(f"[{re.escape(string.punctuation)}]", ' ', cleaned)
    
    # Removing \n endline, or \t tabline
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()
    
    tokens = nltk.word_tokenize(cleaned)
    
    pos_tags = nltk.pos_tag(tokens)
    
    final_tokens = []
    
    for word, tag in pos_tags:
        wn_tag = get_wordnet_pos(tag)
        lemma = lemmatizer.lemmatize(word, pos=wn_tag)
        
        lemma_lower = lemma.lower().strip()
        
        if lemma_lower not in STOP_WORDS and len(lemma_lower) > 2:
            final_tokens.append(lemma_lower)
            
    return ' '.join(final_tokens)

In [ ]:
raw_dataset['Subject'] = raw_dataset['Subject'].fillna("")
raw_dataset['Message'] = raw_dataset['Message'].fillna("")

In [13]:
print(f"Number of records before deleting duplicated: {len(raw_dataset)}")

Number of records before deleting duplicated: 33716

In [14]:
# Drop Duplicated Record been detected when performing EDA
raw_dataset = raw_dataset.drop_duplicates(subset=['Subject', 'Message'], keep='first')

In [15]:
print(f"Number of records after dropped duplicated: {len(raw_dataset)}")

Number of records after dropped duplicated: 30494

In [16]:
preprocessed_dataset['Subject'] = raw_dataset['Subject'].apply(preprocessing_message)
preprocessed_dataset['Message'] = raw_dataset['Message'].apply(preprocessing_message)
preprocessed_dataset['Label'] = raw_dataset['Spam/Ham']

In [17]:
# Remove record has null at both Subject and Message column
preprocessed_dataset = preprocessed_dataset[
    (preprocessed_dataset['Subject'] != '') | (preprocessed_dataset['Message'] != '')
]

## Previewing the preprocessed data

In [18]:
preprocessed_dataset.info()

<class 'pandas.DataFrame'>
Index: 30479 entries, 0 to 33714
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Label    30479 non-null  str
 1   Subject  30479 non-null  str
 2   Message  30479 non-null  str
dtypes: str(3)
memory usage: 952.5 KB

In [19]:
preprocessed_dataset[["Subject", "Message"]].head(20)

,Subject,Message
0,christmas tree farm picture,
1,vastar resource inc,gary production high island large block commence saturday gross carlos expect gross tomorrow vastar gross production george forward george weissman hou ect daren farmer carlos rodriguez hou ect ect george weissman hou ect ect melissa graf hou ect ect subject vastar resource inc carlos please call linda get everything set estimate come tomorrow increase follow day base conversation bill fischer bmar forward daren farmer hou ect enron north america corp george weissman daren farmer hou ect ect gary bryan hou ect ect melissa graf hou ect ect subject vastar resource inc darren attached appear nomination vastar resource inc high island large block previously erroneously refer well vastar expect well commence production sometime tomorrow tell linda harris get telephone number gas control provide notification turn tomorrow linda number record voice fax would please see someone contact linda advise submit future nomination via mail fax voice thanks george forward george weissman hou ect linda harris george weissman hou ect ect subject effective mscf min ftp time hour hour hour hour hour hour hour hour hour hour hour hour hour hour hour hour hour
2,calpine daily gas nomination,calpine daily gas nomination doc
3,issue,fyi see note already stella forward stella morris hou ect sherlyn schumack stella morris hou ect ect howard camp hou ect ect subject issue stella already take care yesterday thanks howard camp stella morris hou ect ect sherlyn schumack hou ect ect howard camp hou ect ect stacey neuweiler hou ect ect daren farmer hou ect ect subject issue stella work stacey daren resolve forward howard camp hou ect sherlyn schumack howard camp hou ect ect subject issue create accounting arrangement purchase unocal energy meter deal track volume deal expire
4,meter nov allocation,fyi forward lauri allen hou ect kimberly vaughn lauri allen hou ect ect mary smith hou ect ect subject meter nov allocation lauri put strangas gas get contract daren forward kimberly vaughn hou ect lauri allen kimberly vaughn hou ect ect anita luong hou ect ect howard camp hou ect ect mary smith hou ect ect subject meter nov allocation kim anita volume show allocate reliant contract november nomination reliant point november therefore volume allocate contract please make sure volume move reliant contract prior november close thanks
5,mcmullen gas,jackie since inlet river plant shut last day flow meter mcmullen gas divert meter hpl buy residue gas gas teco vastar vintage tejones swift still see active deal meter path manager teco vastar vintage tejones swift also see gas schedule pop meter please advice need resolve soon possible settlement send payment thanks
6,meter jan,george need follow jan zero receipt package allocate flow deliv package jan zero receipt package zero deliv package buyback incorrectly nominate transport contract ect receipt let know
7,dun number change,fyi forward gary payne hou ect antoine pierre tommy yanowski hou ect ect kathryn bussell hou ect ect gary payne hou ect ect diane niestrath hou ect ect romeo souza hou ect ect michael eiben hou ect ect clem cernosek hou ect ect scotty gilbert hou ect ect dave nommensen hou ect ect david rohan hou ect ect kevin heal cal ect ect richard pinion hou ect ect mary gosnell hou ect ect jason moore hou ect ect samuel schott hou ect ect bernice rodriguez hou ect ect subject dun number change make change wednesday december agree problem dnb number change please notify otherwise make change scheduled dunns number change counterparty number cinergy resource inc energy dynamic management inc south jersey resource group llc transalta energy marketing inc philadelphia gas work thanks rennie
8,king ranch,two field gas difficulty unify system cage ranch since processing agreement accomodates gas king ranch understanding hpl sell liquid king ranch deliver stratton also understanding cent fee deliver gas need method accomodate volume flow hpl meter gas reflect trans usage ticket since nominate processing agreement either need input point nom hpl krgp meter match nom meter deal purchase sale king ranch take title gas need input sitara meter appropriate rate currently input point nom krgp accomodate flow divert gas current interstate sale make forest oil processing agreement accomodate flow meter king ranch understanding agreement originally setup texaco processing agreement need confirmation gas meter nominate contract agreement reassign hplc currently still hplr gas nominate transport agreement need accomodate flow volume hpl pipe either point nom sitara deal meter
9,entex transistion,thanks much memo would like reiterate support two key issue thu best luck new assignment howard work hard great job please shy ask question entex critical texas business critical team timely accurate rita thanks set account team communication critical success encourage keep inform time impact business significant additionally high profile want assure top quality thanks effort let know anything help provide additional support rita wynne janet wallis hou ect ect ami chokshi corp enron enron howard camp hou ect ect thu nguyen hou ect ect kyle lilly hou ect ect stacey neuweiler hou ect ect george grant hou ect ect julie meyers hou ect ect daren farmer hou ect ect kathryn cordes hou ect ect rita wynne hou ect lisa csikos hou ect ect brenda herod hou ect ect pamela chamber corp enron enron subject entex transistion purpose email recap kickoff meeting hold yesterday member commercial volume managment concernig entex account effective january thu nguyen volume managment group take responsibility allocate entex contract howard thu begin training month continue transition account next month entex thu primary account especially first month learn allocation process contract howard continue lead responsibilites within group available question backup necessary thanks howard hard work account year initial phase transistion would like organize entex account team team member front office back office would meet point month discuss issue relate scheduling allocation settlement contract deal etc hopefully give chance identify resolve issue finalization process learn relative respective area allow newcomer get speed account well would encourage everyone attend meeting initially believe critical part success entex account assistant coordinate initial meeting early anyone question concern please feel free call stop thanks advance everyone cooperation julie please add thu confirmation distribution list
10,entex transistion,purpose email recap kickoff meeting hold yesterday member commercial volume managment concernig entex account effective january thu nguyen volume managment group take responsibility allocate entex contract howard thu begin training month continue transition account next month entex thu primary account especially first month learn allocation process contract howard continue lead responsibilites within group available question backup necessary thanks howard hard work account year initial phase transistion would like organize entex account team team member front office back office would meet point month discuss issue relate scheduling allocation settlement contract deal etc hopefully give chance identify resolve issue finalization process learn relative respective area allow newcomer get speed account well would encourage everyone attend meeting initially believe critical part success entex account assistant coordinate initial meeting early anyone question concern please feel free call stop thanks advance everyone cooperation julie please add thu confirmation distribution list
11,lst rev dec josey ranch nom,fyi forward susan trevino hou ect bob withers susan trevino hou ect ect stretch brennan kevin mclarney taylor vance mail subject lst rev dec josey ranch nom susan discuss change miss discuss last week apologize omission check field personnel anticipate reduction due well production decrease effective send separate email intra day change wednesday revise december effective setup josey use btu mcf gas delivery hpl mmbtu kri net reduction mmbtu mmbtu hpl bob withers kcs energy san felipe suite houston voice mail page
12,rev dec josey ranch nom,forward susan trevino hou ect bob withers susan trevino hou ect ect stretch brennan kevin mclarney taylor vance mail subject rev dec josey ranch nom revise december effective setup josey use btu mcf gas delivery hpl mmbtu kri net reduction mmbtu mmbtu hpl bob withers kcs energy san felipe suite houston voice mail page
13,unify close schedule,following close schedule come month year end please keep mind following key time unify sitara bridge back thursday dec error must clear time mass draft thursday even dec accrual process begin friday morning dec group impact accrual please ensure necessary people available support need enron holiday please feel free contact question thank melissa
14,meter nov,aimee sitara deal meter expire oct settlement unable draft invoice deal deal either need extend new deal need set please let know resolve need resolve friday dec
15,meter nov,daren could please resolve issue howard office next two day please let george know thanks aimee forward aimee lannou hou ect howard camp aimee lannou hou ect ect daren farmer hou ect ect stacey neuweiler hou ect ect mary smith hou ect ect subject meter nov aimee sitara deal meter expire oct settlement unable draft invoice deal deal either need extend new deal need set please let know resolve need resolve friday dec
16,texas log,name home pager george grant charlotte hawkins aimee lannou robert lloyd stella morris susan trevino kim vaughn jackie young carlos rodriguez mandy allen
17,lyondell citgo,late understanding buyback place new deal day begin currently buyback provision ken howard camp gary lamphier hou ect ect kenneth seaman hou ect ect kristen hanson hou ect ect tina valadez hou ect ect howard camp hou ect ect subject lyondell citgo gary notify possibility buyback effective lyondell citgo could please inform via mail status buyback review
18,hpl fuel gas buy back december,fyi forward gregg lenart hou ect enron north america corp sally shuler enron gregg lenart hou ect ect subject hpl fuel gas buy back december forward sally shuler gpgfin enron michael mitcham jam prentice gpgfin enron enron kerry roper gpgfin enron enron sally shuler gpgfin enron enron mark diedrich gpgfin enron enron paul fox ecf enron enron subject hpl fuel gas buy back december egp fuel fuel sell back mmbtu day start hpl mmbtu anyone question please let know thanks
19,meter falfurrias,daren need help resolve issue deal reference meter could find anything cpr contract show represent sale amount thanks stella

## Export the preprocessed data

In [20]:
preprocessed_dataset.to_csv('./data/preprocessed/enron_spam_data_preprocessed.csv',index=False)